api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('sessions/<slug:session_key>/', views.Sessions.as_view(), name='api-sessions'),
    path('surveys/<int:survey_id>/', views.Surveys.as_view(), name='api-surveys'),
]

framework/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as account_views
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls, name='admin'),
    # path('register/', account_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('api/', include('api.urls', namespace='api')),

    #path('surveys/', include('surveys.urls', namespace='surveys')),

    # Installed apps
    path('tinymce/', include('tinymce.urls')),

]

urlpatterns += i18n_patterns(
    path('surveys/', include('surveys.urls', namespace='surveys')),
    path('', include('home.urls', namespace='home')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

riskywally/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as account_views
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls, name='admin'),
    # path('register/', account_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('api/', include('api.urls', namespace='api')),

    # path('surveys/', include('surveys.urls', namespace='surveys')),
    # Installed apps
    path('tinymce/', include('tinymce.urls')),
    path('jet_api/', include('jet_django.urls')),

]

urlpatterns += i18n_patterns(
    path('surveys/', include('surveys.urls', namespace='surveys')),
    path('', include('home.urls', namespace='home')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

surveys/urls.py
from django.urls import path
from surveys.views import SurveysView, SurveyUptateView
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'surveys'

urlpatterns = [
    path('', SurveysView.as_view(), name='surveys'),
    path('<int:pk>/', views.survey_detail, name='survey'),
    path('new/', login_required(views.create_survey), name='create-survey'),
    path('<int:pk>/delete/', login_required(views.delete_survey), name='delete-survey'),
    path('<int:pk>/edit/', login_required(SurveyUptateView.as_view()), name='edit-survey'),
    path('<int:pk>/delete-sessions/', login_required(views.delete_sessions), name='delete-sessions'),

    path('<int:survey_id>/introduction/', views.introduction, name='introduction'),
    path('<int:survey_id>/load/', views.load_set, name='load-survey'),
    path('<int:survey_id>/<slug:session_key>/', views.session_detail, name='session'),
    path('<int:survey_id>/<slug:session_key>/instructions/', views.instructions, name='instructions'),
    path('<int:survey_id>/<slug:session_key>/instructions2/', views.instructions2, name='instructions2'),
    path('<int:survey_id>/<slug:session_key>/testround/', views.testround, name='testround'),
    path('<int:survey_id>/<slug:session_key>/testround_end/', views.testround_end, name='testround_end'),

    path('<int:survey_id>/<slug:session_key>/survey/ready/', views.survey_ready, name='survey-ready'),
    path('<int:survey_id>/<slug:session_key>/block/ready/', views.block_ready, name='block-ready'),

    path('<int:survey_id>/<slug:session_key>/trial/', views.trial, name='trial'),
    path('<int:survey_id>/<slug:session_key>/trial/save/<int:trial_id>/', views.save_trial, name='save-trial'),

    path('<int:survey_id>/<slug:session_key>/training/', views.training, name='training'),
    path('<int:survey_id>/<slug:session_key>/save-training/', views.save_training, name='save-training'),

    path('<int:survey_id>/<slug:session_key>/end/', views.end, name='end'),

]

surveys/models.py
from django.db import models
from tinymce.models import HTMLField
from django.urls import reverse
from django.conf import settings

# Redirect constant
REDIRECTS = (
(0, 'Pre'),
(1, 'Intermediate'),
(2, 'Post')
)

# Survey model
class Survey(models.Model):
    name = models.CharField(
        max_length=255,
        verbose_name='The surveys name',
        help_text="Give survey a name"
    )

    description = models.TextField(
        verbose_name='Short description of the survey',
        help_text='Give the survey a short description, so that others know what it us'
    )

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    introduction = HTMLField(blank=True)
    ready = HTMLField(blank=True)
    end = HTMLField(blank=True)
    ntrials = models.IntegerField(default=1, verbose_name='Trial multiplicator')
    ntraining = models.IntegerField(default=3, verbose_name='Training number')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_DEFAULT, default=1)

    # Returns name in the admin panel
    def __str__(self):
        return self.name

    # Defines redirect url for generic views
    def get_absolute_url(self):
        return reverse('surveys:survey', kwargs={'pk':self.pk})

# Session model
class Session(models.Model):
    key = models.CharField(max_length=255, primary_key=True)

    survey = models.ForeignKey(
        Survey,
        on_delete=models.CASCADE,
        verbose_name='Related survey')

    start_date = models.DateTimeField(auto_now_add=True)
    end_date = models.DateTimeField(auto_now=True)
    ip_address = models.GenericIPAddressField(
        protocol = 'both',
        unpack_ipv4=True
    )
    participantID = models.IntegerField(null=True)
    comment = models.TextField(null=True)

    # Returns name in the admin panel
    def __str__(self):
        return str(self.key)

    class Meta:
        ordering = ['-start_date']

# Trial model
class Trial(models.Model):
    sessionkey = models.ForeignKey(Session, on_delete=models.CASCADE)
    blockcounter = models.IntegerField(null=True)
    context = models.CharField(max_length=255)
    ai_method = models.CharField(max_length=255)
    explanation_approach = models.CharField(max_length=255)
    ai_recommendation = models.CharField(max_length=255)
    label = models.CharField(max_length=255)
    choice = models.CharField(max_length=255)
    rating_1 = models.IntegerField(null=True)
    rating_2 = models.IntegerField(null=True)
    rating_3 = models.IntegerField(null=True)
    decision = models.IntegerField(null=True)
    certainty = models.IntegerField(null=True)
    start_date = models.DateTimeField(auto_now_add=True)
    end_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ['id']

#Redirect model
class Redirect(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    url = models.URLField(verbose_name='Redirect URL', max_length=255)
    purpose = models.IntegerField(verbose_name="Purpose", choices=REDIRECTS)

    # Returns name in the admin panel
    def __str__(self):
        return str(self.url)

    class Meta:
        ordering = ['purpose']

# Model for a specific factor set
class SetFactor(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, verbose_name="Factor name")
    blockfactor = models.BooleanField(verbose_name="Block factor")
    slug = models.SlugField(verbose_name='Factor slug')

    # Returns name in the admin panel
    def __str__(self):
        return str(self.name)

# Model for level of a factor set
class SetLevel(models.Model):
    set_factor = models.ForeignKey(SetFactor, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, verbose_name="Factor Name")
    value = models.IntegerField(verbose_name="Factor value")
    slug = models.SlugField(verbose_name='Level slug')

    # Returns name in the admin panel
    def __str__(self):
        return str(self.name + ' [' + str(self.value) + ']')

surveys/forms.py
from django import forms
from .models import Survey, Session

# Form for creating a Survey
class SurveyCreateFrom(forms.ModelForm):
    class Meta:
        model = Survey
        fields = [
            'name',
            'description',
            'introduction',
            'ready',
        ]
# Form for saving a participants ID and comment at the end of the survey
class ParticipantIDForm(forms.ModelForm):
    class Meta:
        model = Session
        fields = [
            'participantID',
            'comment'
        ]

surveys/templates/surveys/end.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
<div class="uk-container uk-margin-top">
  <p>{{survey.end|safe}}</p>
  <a class="uk-button uk-button-default" href="mailto:liehner@comm.rwth-aachen.de">{% trans "Contact us via mail" %}</a>
  <form class="uk-form-stacked uk-margin-medium-top" method="post">
    {% csrf_token %}
    <legend class="uk-legend">{% trans "Participant" %}</legend>
    <div class="uk-margin">
      <label class="uk-form-label" for="form-stacked-text">ID</label>
      <div class="uk-form-controls">
        {{ form.participantID|add_class:"uk-input" }}
      </div>
    </div>
    <div class="uk-margin">
      <label class="uk-form-label" for="form-stacked-text">{% trans "Comment" %}</label>
      <div class="uk-form-controls">
        {{ form.comment|add_class:"uk-textarea" }}
      </div>
    </div>
    <button class="uk-button uk-button-secondary" type="submit" name="button">{% trans "Save & back to start screen" %}</button>
  </form>
  <img class="uk-float-right uk-visible@m" src="{% static 'surveys/img/success.png'%}">
</div>
{% endblock %}

surveys/templates/surveys/instructions.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<br />
<div class="uk-container uk-margin-top uk-animation-fade">
    <h1>Das Experiment</h1>
    <p>{{survey.ready|safe}}</p>
    <a class="uk-button uk-button-primary uk-margin-large-bottom" style="background-color: #707070" href="{% url 'surveys:instructions2' survey.id session.key %}" uk-toggle>{% trans "Weiter" %}</a>
    <img class="uk-float-right uk-visible@m" width="300" src="{% static 'surveys/img/process.png'%}">
</div>

<div class="hidden">
    <input id="trial-redirect" name="trial-redirect" type="hidden" value="{% url 'surveys:instructions2' survey.id session.key %}">
</div>

{% load static %}
<script src="{% static 'surveys/js/checkbox_validation.js' %}"></script>
{% endblock %}

surveys/templates/surveys/instructions2.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<br />
<div class="uk-container uk-margin-top uk-animation-fade">
    <h1>Die KI-Methoden</h1>
    <p style="font-size:19px; text-align: justify">
        Falls Sie die Funktionsweisen der einzelnen KI-Methoden nicht im Detail nachvollziehen k&oumlnnen, machen Sie sich keine Sorgen! Die Erkl&aumlrungen dienen lediglich dazu, Ihnen eine ungef&aumlhre Vorstellung der Funktionsweisen zu vermitteln. F&uumlr die Aufgabenbearbeitung ben&oumltigen Sie kein detailliertes Verst&aumlndnis.
    </p>
    <br />
    <table>
        <colgroup>
            <col style="width:45%">
            <col style="width:5%">
            <col style="width:5%">
            <col style="width:45%">
        </colgroup>
        <tr>
            <td valign="top">
                <b style="font-size:19px;">N&aumlchste-Nachbarn-Klassifikation</b><br /><br />
                <img class="uk-visible@m" src="{% static 'surveys/img/knn.png'%}"><br />
                <p style="font-size:17px;text-align: justify">Bei dieser Methode werden zu einem gegebenen Objekt (hier: rot) &aumlhnliche Objekte, sog. „Nachbarn“ herangezogen, um den Wert der Zielgr&ouml&szlige zu prognostizieren. Der Wert, der unter den Nachbarn am h&aumlufigsten vorkommt (hier: Klasse B), wird als Wert der Zielgr&ouml&szlige festgelegt. Kommen zwei oder mehr Werte gleich h&aumlufig vor, so wird zwischen diesen zuf&aumlllig entschieden.</p>

            </td>
            <td style="border-right: thin solid #d6d6d6;"></td>
            <td></td>
            <td valign="top">
                <b style="font-size:19px;">Support-Vektor-Maschine</b><br /><br />
                <img class="uk-visible@m" src="{% static 'surveys/img/svm.png'%}">
                <p style="font-size:17px;text-align: justify">Bei dieser Methode wird jedes Objekt durch einen Vektor in einem Vektorraum repr&aumlsentiert. Die verschiedenen Objektklassen (hier: Klasse A und Klasse B) werden so voneinander getrennt, dass zwischen verschiedenen Klassen ein m&oumlglichst gro&szliger Bereich frei von Objekten bleibt. Ein neues Objekt wird entsprechend seiner Position im Vektorraum mit Hilfe der Trennungslinien bzw. -ebenen zugeordnet.</p>
            </td>
        </tr>
    </table>
    <br />
    <p style="font-size:19px; text-align: justify">
        Bevor es richtig losgeht, starten wir mit einer Testrunde, damit Sie sich mit dem System vertraut machen k&oumlnnen.
    </p>
    <a class="uk-button uk-button-primary uk-margin-large-bottom" style="background-color: #707070" href="{% url 'surveys:testround' survey.id session.key %}" uk-toggle>{% trans "Zur Testrunde" %}</a>
</div>

<div class="hidden">
    <input id="trial-redirect" name="trial-redirect" type="hidden" value="{% url 'surveys:testround' survey.id session.key %}">
</div>

{% load static %}
<script src="{% static 'surveys/js/checkbox_validation.js' %}"></script>
{% endblock %}

surveys/templates/surveys/session_detail.html
{% extends 'base.html'%}
{% block body%}
{% load static %}
<div class="uk-container uk-margin-top uk-margin-large-bottom">
  <a href="{% url 'surveys:survey' session.survey.id %}" uk-icon="icon: chevron-left" uk-tooltip="Back to overview"></a>
  <h2 class="uk-heading-small uk-heading-bullet">{{session.key}}</h2>
  <ul uk-tab>
    <li><a href="#">General Information</a></li>
    <li><a href="#">Trials</a></li>
    <li><a href="#">Statistics</a></li>
  </ul>
  <div class="uk-switcher">
    <div class="uk-animation-slide-bottom-small">
      <span class="uk-float-right">ID: <span class="uk-label">{{session.participantID}}</span></span>
      <p>Key: <span class="uk-badge">{{session.key}}</span></p>
      <p class="uk-article-meta">Start date: {{session.start_date}}.</p>
      <p class="uk-article-meta">End date: {{session.end_date}}.</p>
      <p>IP-Address: <code>{{session.ip_address}}</code> </p>
      <dl class="uk-description-list">
        <dt>Comment</dt>
        <dd>{{session.comment}}</dd>
      </dl>
      <h3>Interview</h3>
      <hr>
      {% if session.audio %}
      <audio controls>
        <source src="{{session.audio.url}}" type="audio/mp3">
        Your browser does not support the audio element.
      </audio>
      <a href="{% url 'api:transcribe' session.key %}" class="uk-button uk-button-default uk-margin-medium-left">Transcribe</a>
      <h3>Transcription</h3>
      <hr>
      <p>{{session.transcript}}</p>
      {% else %}
      <a href="{% url 'admin:index' %}" class="uk-button uk-button-default">Upload file</a>
      {% endif %}

    </div>
    <div class="uk-animation-slide-bottom-small">
      <p>Trial count: <span class="uk-badge">{{session.trial_set.count}}</span>
      </p>
      <table class="uk-table uk-table-divider">
        <thead>
          <tr>
            <th>ID</th>
          </tr>
        </thead>
        <tbody>
          {%for trial in session.trial_set.all %}
          <tr>
            <td>{{trial.id}}</td>
          </tr>
          {% endfor %}
        </tbody>

      </table>

      <a href="#" uk-totop uk-scroll></a>
    </div>
  </div>
</div>
<script src="{% static 'surveys/js/session_graphs.js' %}"></script>
<script src="{% static 'surveys/js/transcribe.js' %}"></script>

{% endblock %}

surveys/templates/surveys/survey_detail.html
{% extends 'base.html'%}
{% block body%}
{% load static %}
<div class="uk-container uk-margin-top">
  <a href="{% url 'surveys:surveys' %}" uk-icon="icon: chevron-left" uk-tooltip="Back to overview"></a>
  <h2 class="uk-heading-small uk-heading-bullet">{{survey.name}}</h2>
  <p class="uk-article-meta">Created by <a href="#">{{survey.user}}</a> on {{survey.date_created}}.</p>
  <ul uk-tab>
    <li><a href="#">General Information</a></li>
    <li><a href="#">Redirects</a></li>
    <li><a href="#">Factors</a></li>
    <li><a href="#">Sessions</a></li>
    <li><a href="#">Statistics</a></li>
  </ul>
  <div class="uk-switcher">
    <div class="uk-animation-slide-bottom-small">
      <ul class="uk-iconnav">
        <li><a href="{% url 'surveys:edit-survey' survey.id %}" uk-tooltip="Edit general information" uk-icon="icon: file-edit"></a></li>
        <li><a href="#delete-modal" class="uk-disabled" uk-tooltip="Delete survey" uk-icon="icon: trash" uk-toggle></a></li>
      </ul>
      <div id="delete-modal" class="uk-flex-top" uk-modal>
        <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical">
          <form action="{% url 'surveys:delete-survey' survey.id%}" method="post">
            {% csrf_token %}
            <h2 class="uk-modal-title">Delete survey</h2>
            <p>Do you really want to delete the survey?</p>
            <button class="uk-modal-close-default" type="button" uk-close></button>
            <p class="uk-text-right">
              <button class="uk-button uk-button-default uk-modal-close" type="button">Cancel</button>
              <button class="uk-button uk-button-danger" type="submit">Delete</button>
            </p>
          </form>
        </div>
      </div>
      <h3>Description</h3>
      <hr>
      <p>{{survey.description}}</p>
      <h3>Introduction</h3>
      <hr>
      <p>{{survey.introduction|safe}}</p>
      <h3>Ready text</h3>
      <hr>
      <p>{{survey.ready|safe}}</p>
      <h3>End text</h3>
      <hr>
      <p>{{survey.end|safe}}</p>
    </div>
    <div class="uk-animation-slide-bottom-small">
      <h3>Redirects</h3>
      {% for redirect in survey.redirect_set.all %}
      <p>{{redirect.purpose}} <code>{{redirect.url}}</code></p>
      {% endfor %}
    </div>
    <div class="uk-animation-slide-bottom-small">
      <h3>Factors</h3>
      {% for setfactor in survey.setfactor_set.all %}
      <p class="uk-text-lead">{{setfactor}}</p>
      <ul class="uk-list uk-list-striped">
        {% for level in setfactor.setlevel_set.all %}
        <li>{{level.name}} <code>{{level.slug}}</code> <span class="uk-label uk-align-right"> {{level.value}}</span></li>
        {% endfor %}
      </ul>
      {% endfor %}
    </div>
    <div class="uk-animation-slide-bottom-small">
      <h3>Sessions</h3>
      {% if survey.session_set.all %}
      <button class="uk-button uk-button-danger" href="#" uk-toggle="target: #delete-session-modal" disabled>Delete all</button>
      {% endif %}
      <div id="delete-session-modal" uk-modal>
        <div class="uk-modal-dialog uk-modal-body">
          <form action="{% url 'surveys:delete-sessions' survey.id%}" method="post">
            {% csrf_token %}
            <h2 class="uk-modal-title">Delete sessions</h2>
            <p>Are you sure that you want to delete all the sessions?</p>
            <p class="uk-text-right">
              <button class="uk-button uk-button-default uk-modal-close" type="button">Cancel</button>
              <button class="uk-button uk-button-danger" type="submit">Delete</button>
            </p>
          </form>
        </div>
      </div>
      <p>Number of sessions: <span class="uk-badge">{{survey.session_set.all.count}}</span></p>
      <table class="uk-table uk-table-divider">
        <thead>
          <tr>
            <th class="uk-table-shrink">#</th>
            <th class="uk-table-expand">Session ID</th>
            <th class="uk-width-small">Participant ID</th>
            <th class="uk-width-medium"></th>
          </tr>
        </thead>
        <tbody>
          {%for session in survey.session_set.all %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>{{session.key}}</td>
            <td><span class="uk-label">{{session.participantID}}</span></td>
            <td><a class="uk-button uk-button-default" href="{% url 'surveys:session' survey.id session.key%}">View details</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="uk-animation-slide-bottom-small">
      <input id="api-call-survey" name="api-call-survey" type="hidden" value="{% url 'api:api-surveys' survey.id %}">
      <div class="uk-column-1-2 uk-animation-slide-bottom-small ">
        <div>
          <p>Number of trials: <span class="uk-badge">{{ntrials}}</span></p>
        </div>
        <div>
          <canvas id="scenario_comparison" width="400" height="400"></canvas>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'surveys/js/survey_graphs.js' %}"></script>
{% endblock %}

surveys/templates/surveys/survey_list.html
{% extends 'base.html'%}
{% block body%}
<div class="uk-container uk-margin-top">
  <h2 class="uk-heading-small uk-heading-bullet">Survey list</h2>
  <ul class="uk-iconnav">
    <li><a href="{% url 'surveys:create-survey' %}" uk-icon="icon: plus" uk-tooltip="Create new survey"></a></li>
  </ul>
  <div class="uk-grid-large uk-child-width-1-3 uk-margin-top" uk-grid>
    {% for survey in survey_list %}
    <div class="uk-card uk-card-default uk-card-hover uk-margin-left">
      <div class="uk-card-header">
        <h3 class="uk-card-title">{{ survey.name }}</h3>
      </div>
      <div class="uk-card-body">
        <p>{{survey.description}}</p>
      </div>
      <div class="uk-card-footer">
        <a href="{% url 'surveys:survey' survey.id%}" class="uk-button uk-button-text">Details</a> |
        <a href="{% url 'surveys:introduction' survey.id%}" class="uk-button uk-button-text">Start Survey</a>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

surveys/templates/surveys/survey_ready.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
{% load i18n %}
<div class="uk-container uk-margin-top">
  <h2 class="uk-heading-small">{% trans "Results" %}</h2>
  <p>{% trans "Congratulations! You have finished the training round. Here are your results:" %}</p>
  <a class="uk-button uk-button-default" href="{% url 'surveys:trial' survey.id session.key %}">{% trans "Start real rounds!" %}</a>
  <img class="uk-float-right uk-visible@m" src="{% static 'surveys/img/results.png'%}">
</div>
{% endblock %}

surveys/templates/surveys/testround_end.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
{% load i18n %}
<br />
    <div class="uk-container uk-margin-top">
        <h2 class="uk-heading-small">Super!</h2>
        <p style="font-size:19px">{% trans "Sie haben die Testrunde erfolgreich beendet!" %}</p>
        <p style="font-size:19px;text-align: justify">{% trans "Das Empfehlungssystem hat Ihnen in diesem Fall die bestm&oumlgliche Empfehlung gegeben. Auch wenn Empfehlungssysteme <b>meistens richtig</b> liegen, sollten Sie im Hinterkopf behalten, dass Fehleinsch&aumltzungen nat&uumlrlich bei jedem KI-basierten System auftreten k&oumlnnen." %}</p>
        <p style="font-size:19px">{% trans "Jetzt kann es endlich losgehen!" %}</p>

        <a class="uk-button uk-button-primary uk-margin-large-bottom" style="background-color: #707070" href="{% url 'surveys:trial' survey.id session.key %}">{% trans "Experiment starten" %}</a>
        <img class="uk-float-right uk-visible@m" width="400" src="{% static 'surveys/img/results.png'%}">
    </div>
{% endblock %}

surveys/templates/surveys/training.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
{% load i18n %}
<div id="preload" class="uk-flex uk-height-medium uk-margin uk-text-center">
  <div class="uk-margin-auto uk-margin-auto-vertical uk-width-1-2@s">
    <div uk-spinner="ratio: 3">
    </div>
  </div>
</div>
<div class="content">
    <div class="uk-visible@m">
      <div class="uk-flex uk-flex-center">
        <div id="offcanvas-reveal" uk-offcanvas="mode: reveal; overlay: true">
          <div class="uk-offcanvas-bar">
            <button class="uk-offcanvas-close" type="button" uk-close></button>
            <h3>Trial Details</h3>
            <p>Attemps: <span class="uk-badge">{{attempts}}</span></p>
            <p>Blocknumber: <span class="uk-badge">{{blockcounter}}</span></p>
            <p>Blocksize: <span class="uk-badge">{{size}}</span></p>
          </div>
        </div>
      </div>
    </div>
</div>
<div class="hidden">
  <input id="sessionkey" name="sessionkey" type="hidden" value="{{ session.key }}">
  <input id="blockcounter" name="blockcounter" type="hidden" value="{{ blockcounter }}">
  <input id="trial-id" name="trial-id" type="hidden" value="{{ trial.id }}">
  <input id="language-code" name="language-code" type="hidden" value="{{language}}">
  <input id="save-training" name="save-training" type="hidden" value="{% url 'surveys:save-training' survey.id session.key %}">
  <input id="next-training" name="next-training" type="hidden" value="{% url 'surveys:training' survey.id session.key %}">
</div>
{% load static %}
<script src="{% static 'surveys/js/training.js' %}"></script>
{% endblock %}

surveys/templates/surveys/trial_ready.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
{% load i18n %}
<div class="uk-container uk-margin-top">
  <h2 class="uk-heading-small">{% trans "Ready" %}</h2>
  <p>{% trans "If you ready for the next set of situation click the Go-Button" %}</p>
  <a class="uk-button uk-button-default" href="{% url 'surveys:trial' survey.id session.key %}">{% trans "Go" %}</a>
    <img class="uk-float-right uk-visible@m" src="{% static 'surveys/img/results.png'%}">
</div>

{% endblock %}